CREATE KEYSPACE epsilon WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };

CREATE TABLE epsilon.surge_5145_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5145_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5146_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5147_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5148_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5149_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5150_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5151_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5152_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5153_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5154_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5155_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5156_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5157_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5158_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5159_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5160_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5161_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5162_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0032 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0031 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0030 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0029 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0028 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0027 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0026 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0025 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0024 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0023 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0022 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0021 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0020 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0019 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0018 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0017 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0016 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0015 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0014 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0013 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0012 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0011 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0010 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);

CREATE TABLE epsilon.surge_5163_n0009 (timestamp bigint PRIMARY KEY, latitude decimal,longitude decimal,surge_multiplier decimal);
